<ouc:editor wysiwyg="yes"/>
<div class="col-md-9 col-sm-6 col-xs-12 footer-columns">
	<div class="row">
		<div class="col-sm-6 col-xs-12 footer-center">
			<strong>Location</strong>
			<address>Computer Services Annex<br/>101 Cedar St.<br/>Athens, Georgia 30602</address>
		</div>
		<div class="col-sm-6 col-xs-12 footer-right">
			<strong>Contact Information</strong>
			<ul class="list-unstyled">
				<li>
					<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
					<a href="mailto:oir@uga.edu">Email Us</a>
				</li>
				<li>
					<span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
					<a href="tel:7065423106">706-542-3106</a>
				</li>
				<li>
					<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
					<a href="mailto:eits@uga.edu">Help desk</a> 
				</li>
			</ul>
		</div>
	</div>
</div>